### ISSUE TITLE
I.E. 10 calls external-link-warning switching between pages

### ISSUE THREAD

**Issue by grahamunr** [martinbean/external-link-warning#1]
First of all, awesome plug-in!  Thanks for sharing.  Is there a way to tell IE to not call the warning when you're switching between pages.  As far as I know, this is the only browser that behaves like this.

Thanks!

**Comment by martinbean** [comment]
@grahamunr Just did some Googling. I don’t have access to Internet Explorer, what happens if you change `top.location.host` on [line 10](https://github.com/martinbean/external-link-warning/blob/master/jquery.externalLinkWarning.js#L10) to `window.location.host` instead?

**Comment by grahamunr** [comment]
Awesome.  Thanks for the fast reply!

**Comment by martinbean** [comment]
@grahamunr Just updated my comment above. Take a look and let me know.

**Comment by grahamunr** [comment]
I just tested it and it appears to still be calling the function when navigating to another page.
